### PR TITLE
Scraping calcalist

### PR DESCRIPTION
**Pull request by gidgid**
- Add support for scraping calcalist at: http://www.calcalist.co.il/local/home/0,7340,L-3789,00.html
- Modifies the-marker scraper to fix date issues
- Makes the "all-appointments" pipeline use both the marker & calcalist

### CODE REVIEW

**Comment by OriHoch** [comment]
@gidgid code looks good, but.. this data is available in RSS - 
http://www.calcalist.co.il/GeneralRSS/0,16335,L-3789,00.xml

**Comment by OriHoch** [comment]
alternatively, if you need historical data - you can load the html and parse it directly
page 1 - 
view-source:http://www.calcalist.co.il/Ext/Comp/NominationList/CdaNominationList_Iframe/1,15014,L-0-1,00.html?parms=5543
page 2 - 
view-source:http://www.calcalist.co.il/Ext/Comp/NominationList/CdaNominationList_Iframe/1,15014,L-0-2,00.html?parms=5543
...

**Comment by gidgid** [comment]
Regarding the 2nd comment - this is actually what the first part is doing by getting that from an iframe (the init nomination page) - are you suggesting that I'll avoid that step and go straight to fetching the inside?

**Comment by OriHoch** [comment]
cool, yes - I would generally try hard to avoid webdriver / selenium based scraping whenever possible
in this case, I think it's possible to parse the html directly using pyquery with a single processor

**Comment by gidgid** [comment]
Yup, I definitely agree about avoiding whats not needed. Do you mean I should use pyquery to download the actual HTMLs?
Also, did you mean a single custom processor? If not, how do you intend to remove the other processors (join, concatenate etc)?

**Comment by OriHoch** [comment]
yes, in this case I think a single processor which downloads the source files and parses with pyquery is enough
about the other processors - no need to change that, it's fine

**Pull request merged**
