### PR TITLE
exemptions: decode signed documents

### LINKED ISSUE #68: tenders exemptions should parse signed documents
### reproduction
* goto: http://www.obudget.org/#entity/580050789/publication/574896
* click on the document (`4/12/2015 | חוות דעת מקצועית`)

#### expected
* should get the document

#### actual
* get a url to file with `.signed` extension
  * http://www.obudget.org/api/exemption/document?url=http://www.mr.gov.il/Files_Michrazim/201813.signed
* this file is an XML containing signed government document, which causes a server error
* this .signed file is coming from the exemptions pipeline - so I assume fixing it in the pipelines will fix the api/frontend bug as well

### notes
* need to figure out if API should be fixed as well - to show some error message, or skip .signed files
* the relevant API url -  http://www.obudget.org/api/entity/580050789 (search for .signed)

### PR DESCRIPTION
**Pull request by OriHoch**
* added support for .signed documents in procurement/tenders - it decodes them and saves in /var/datapackages/procurement/tenders/scraper/Files_Michrazim/
* the link attribute in the documents json array is replaced with path to this file
* I guess some adjustment will be needed to have the frontend handle this properly

related issue: #68

### CODE REVIEW

**Comment by OriHoch** [comment]
@akariv I'm not sure how to handle the unsigned files
I'm currently storing them at /var/datapackages/procurement/tenders/scraper/Files_Michrazim/
and refering to that diretory in the link which is stored in DB

**Comment by OriHoch** [comment]
in knesset-data-pipelines I transitioned to use minio server for object storage

it's s3 compatible and very lightweight so it allows to require it for dev as well

`docker run -p9000:9000 minio/minio server /data`

**Comment by akariv** [comment]
This is cool, but where is the data stored?
One reason to use S3 is that it's cheap (and reliable) storage and does not pass through the application server.

**Comment by OriHoch** [comment]
minio is S3 compatible, so you can use S3 in production

**Comment by akariv** [comment]
Ah, that's what you meant - use it for dev... cool then :)

**Comment by OriHoch** [comment]
Depends on what you store there

If you only store current data in minio and do backups to S3 - it makes sense to deploy your own minio server (or cluster..)

For knesset-data I currently assigned a 50GB persistent disk for our production minio server - I expect this to last a long time and it only costs ~0.5$ per month...

**Comment by akariv** [comment]
In this scenario we don't really have current vs previous data.  There's a list of documents that's slowly increasing, and never changing.
My main concern here is not the cost of storage, but actually serving these static files on my machines. 

However, to assess how much data it is: we have about 100K records, each one has a few documents - so ~500K documents. Each document is usually a scanned PDF, so let's say ~100KB on average - we get to 50GB). Since not all of them are signed, then it's probably just a fraction of those that actually need storing. And that's not a lot of data.

So let's keep it this way for now, with one modification - we need to document link to be the actual download link (i.e. under https://next.obudget.org/datapackages/tenders/ ...)

**Comment by OriHoch** [comment]
@akariv - I was just fixing according to your comments - to use S3 / object storage

is that not needed and filesystem is enough?

**Comment by OriHoch** [comment]
I'll open a new PR

**Pull request merged**
